module.exports = {
	siteURL: process.env.URL || 'http://localhost:8080',
	siteName: 'the Philip Jones',
	siteDescription: "Hey! I'm Philip.",
	siteImage: '/assets/images/site/siteImage.jpg',
	lang: 'en',
	locale: 'en_us',
	authorName: 'Philip Jones',
	authorURL: 'thephilipjones.com',
	authorEmail: 'philip@thephilipjones.com',
	twitterSite: 'thephilipjones',
	twitterCreator: 'thephilipjones',
	address: {
		// street: '123 Main Street',
		city: 'Reston',
		state: 'VA',
		zip: '',
		// phoneDisplay: '+1 (123) 456-7890',
		// phoneCall: '+11234567890',
		email: 'philip@thephilipjones.com',
	},
}
